### PR TITLE
Fixed indexing bug in crossCleanT5 kernel

### PR DESCRIPTION
**Pull request by ariostas**

### CODE REVIEW

**Comment by slava77** [comment]
> _ No description provided. _

It would be nice to self-document the update a bit better.

I suppose before it's merged we will have the standard comparisons (physics and timing) included as well.

**Comment by ariostas** [comment]
Here are the standard comparisons.

As for timing, nothing changed since the fix is a very simple one. This comparison was run on lnx7188.

Master (https://github.com/SegmentLinking/TrackLooper/commit/7ec62483c714a8d9bb458b07a618f07a43792e45):
```
Total Timing Summary
Average time for map loading = 8424.24 ms
Average time for input loading = 19677.6 ms
Average time for SDL::Event creation = 0.0874656 ms
   Evt    Hits       MD       LS      T3       T5       pLS       pT5      pT3      TC       Reset    Event     Short             Rate
   avg      9.4      2.2      0.4      2.8      3.3      1.0      1.5      1.2      1.2      7.2      30.2      19.9+/-  2.2      35.7   explicit[s=1]
   avg     17.8      2.5      0.5      4.8      5.7      1.0      3.8      3.2      1.6     11.0      52.0      33.2+/-  6.0      29.8   explicit[s=2]
   avg     39.3      2.8      0.6      9.0     11.4      1.2      8.3      6.8      2.1     26.6     107.9      67.5+/- 16.4      29.4   explicit[s=4]
   avg     67.7      2.7      0.5     14.4     18.0      1.2     14.2     11.2      1.8     50.8     182.5     113.6+/- 45.9      33.0   explicit[s=6]
   avg     94.9      2.6      0.5     18.1     24.2      1.1     22.2     16.5      1.9     69.4     251.4     155.4+/- 52.5      33.7   explicit[s=8]
   avg      4.9      2.2      0.4      1.9      1.9      1.0      1.4      1.2      1.2      0.6      16.8      10.9+/-  2.2      20.0   explicit_cache[s=1]
   avg      7.1      2.5      0.4      2.7      2.5      1.0      2.1      1.6      1.7      1.0      22.6      14.5+/-  3.2      15.3   explicit_cache[s=2]
   avg     11.6      3.0      0.7      4.3      4.0      1.2      3.3      2.4      2.8      1.4      34.7      21.9+/-  6.5      11.0   explicit_cache[s=4]
   avg     18.3      4.2      1.3      6.6      6.2      1.3      5.0      3.7      4.0      2.1      52.7      33.1+/-  8.9       9.4   explicit_cache[s=6]
   avg     26.4      4.9      1.5      7.8      8.1      1.5      6.8      4.6      5.0      3.1      69.6      41.8+/- 13.1       9.8   explicit_cache[s=8]
```

This PR (https://github.com/ariostas/TrackLooper/commit/fc6e0e025b85a0c434954e874c0e076b2875f1c3):
```
Total Timing Summary
Average time for map loading = 8331.22 ms
Average time for input loading = 19570.9 ms
Average time for SDL::Event creation = 0.0910078 ms
   Evt    Hits       MD       LS      T3       T5       pLS       pT5      pT3      TC       Reset    Event     Short             Rate
   avg      9.8      2.2      0.4      2.8      3.3      1.0      1.4      1.2      1.2      7.0      30.3      19.6+/-  2.1      32.5   explicit[s=1]
   avg     17.1      2.5      0.5      4.8      5.2      1.0      3.0      3.1      1.6     11.5      50.3      32.2+/-  6.1      29.1   explicit[s=2]
   avg     37.8      2.7      0.6      8.6     11.5      1.1      8.8      7.2      2.0     26.1     106.4      67.6+/- 17.2      29.8   explicit[s=4]
   avg     65.3      2.8      0.5     15.1     19.4      1.1     13.6     10.8      2.0     40.8     171.4     105.0+/- 29.7      30.4   explicit[s=6]
   avg     95.0      2.7      0.5     18.7     25.1      1.1     19.5     13.9      1.9     77.5     255.7     159.7+/- 55.4      34.3   explicit[s=8]
   avg      4.7      2.2      0.4      1.9      1.9      1.0      1.3      1.1      1.2      0.5      16.3      10.6+/-  2.1      19.1   explicit_cache[s=1]
   avg      6.7      2.6      0.5      2.9      2.7      1.0      2.1      1.7      1.8      1.0      23.0      15.2+/-  3.5      12.8   explicit_cache[s=2]
   avg     11.3      3.1      0.7      4.2      4.1      1.1      3.3      2.4      2.7      1.5      34.4      21.9+/-  5.6      10.6   explicit_cache[s=4]
   avg     17.5      4.1      1.2      6.1      5.9      1.3      4.9      3.4      3.8      2.1      50.4      31.6+/- 10.1      10.2   explicit_cache[s=6]
   avg     25.0      4.8      1.6      8.5      8.5      1.5      6.6      4.5      5.2      2.7      68.9      42.4+/- 15.5       9.7   explicit_cache[s=8]
```

Here are the comparison and performance plots.

Comparison: [here](https://www.classe.cornell.edu/~ar2285/www/LST/PR319/crossCleanT5_fix_7ec624-PU200_fc6e0e-PU200/summary/)
Master: [here](https://www.classe.cornell.edu/~ar2285/www/LST/PR319/master_PU200_NEVT-1_7ec624-PU200/summary/)
This PR: [here](https://www.classe.cornell.edu/~ar2285/www/LST/PR319/crosCleanT5_fix_PU200_NEVT-1_fc6e0e-PU200/summary/)

**Comment by slava77** [comment]
> As for timing, nothing changed since the fix is a very simple one.

pT5 seems a bit faster

> Comparison: [here](https://www.classe.cornell.edu/~ar2285/www/LST/PR319/crossCleanT5_fix_7ec624-PU200_fc6e0e-PU200/summary/)

some small drop in efficiency
imageimage

and quite a significant drop in the duplicate rate
image


Not surprisingly, most loss of efficiency is in T5s
imageimage

**Comment by GNiendorf** [comment]
I wasn't there for the discussion today, but are there any objections to merging this PR in? @slava77

**Review by slava77 — APPROVED** [review]

**Comment by slava77** [comment]
> I wasn't there for the discussion today, but are there any objections to merging this PR in? @slava77

no, I guess someone needed to be a volunteer as a reviewer

**Pull request merged**
