### PR TITLE
pLS new score

### PR DESCRIPTION
**Pull request by bsathian**
Fixes pLS score computation, but does not use it while adding pLS in TC collection

https://www.classe.cornell.edu/~bsathian/pLS_PR_new/efficiencies/eff_plots__GPU_explicit_cache_41dd58fDIRTY_PU200/mtv/TCE_AllTypes_h_duplrate_numer_pt_eff.pdf

### CODE REVIEW

**Comment by bsathian** [comment]
pLS_timing

**Comment by bsathian** [comment]
Comparison plots: https://www.classe.cornell.edu/~bsathian/pLS_PR_new/efficiencies/eff_comparison_plots__41dd58fDIRTY_explicit_cache_72b6266_explicit_cache_PU200/TCE_AllTypes__etacoarse.png

**Comment by slava77** [comment]
> Comparison plots: https://www.classe.cornell.edu/~bsathian/pLS_PR_new/efficiencies/eff_comparison_plots__41dd58fDIRTY_explicit_cache_72b6266_explicit_cache_PU200/TCE_AllTypes__pt.pdf

do we have an html page setup to display these comparison plots?
As we have seen previously from pre-PR slides the fake rate goes up. This can be an acceptable regression considering that it's a bug fix, but more work may be needed to make tighter selections.
It would be more clear after the categorization plot is made with this PR.



For the timing plot here
> pLS_timing

vs in #163:  in #163

it's nice to see little impact on the total or even individual times

**Comment by slava77** [comment]
> This can be an acceptable regression considering that it's a bug fix, but more work may be needed to make tighter selections.

I implied that this selection review would happen in a follow up PR(s)

**Pull request merged**
