### PR TITLE
Script for validating the efficiency of duplicate objects

### PR DESCRIPTION
**Pull request by VourMa**
This PR includes a validation script to print info on the duplication of matching in the sim track, TC, pT5, pT3 and T5 collections.

A table with the results can be found [here](https://docs.google.com/spreadsheets/d/1RGS98NUFv17jSe4R5w2qu6XCqOczH30wNN3FWd92s7U/edit?usp=sharing).

### CODE REVIEW

**Comment by tresreid** [comment]
Is there a pt/eta requirement for "good sim". I find it strange that we are still getting <40% here.

**Comment by tresreid** [comment]
Also it might be good to add the total fake rate

**Comment by VourMa** [comment]
> @VourMa Is there a pt/eta requirement for "good sim". I find it strange that we are still getting <40% here.

Indeed, it is low. There is an |η| < 2.4 cut but no pT cut. Given that we expect a high number of very low-pT tracks in the PU200 sample, I can see how this becomes an issue.
On the other hand, I have also run the MuonGun and MuonGun_highE samples (see other sheets in the GoogleSheet). In the latter, the matching efficiency is 100%, which makes sense, given the above.

**Comment by VourMa** [comment]
> Also it might be good to add the total fake rate

By this, do you mean the addition of cells B12, B18, B24, B30 in the sheet?

**Comment by tresreid** [comment]
> > Also it might be good to add the total fake rate
> 
> By this, do you mean the addition of cells B12, B18, B24, B30 in the sheet?

Yeah, just to have everything easily accessible. so we would have the efficiency, duplicate rate (and breakdown) and fake rate for everything we make all in one place. A summary line.

**Comment by VourMa** [comment]
> > > Also it might be good to add the total fake rate
> > 
> > 
> > By this, do you mean the addition of cells B12, B18, B24, B30 in the sheet?
> 
> Yeah, just to have everything easily accessible. so we would have the efficiency, duplicate rate (and breakdown) and fake rate for everything we make all in one place. A summary line.

Yes, this is going to be useful. I added this to the sheet and to the script.

**Pull request merged**
