### PR TITLE
Bug fix for applying pT5 r-z chi2

### PR DESCRIPTION
**Pull request by YonsiG**
We would like to apply r-z chi2 only for pT5 < 5GeV in the algorithm. However, the original check in the code is problematic: it uses the pixelRadius < 5*kR1GeVf, but the pixelRadius is not defined yet. Bug fix and the efficiency is improved by not applying r-z cut on high pt pT5 tracks.

### CODE REVIEW

**Comment by YonsiG** [comment]
this is the slides comparing the effect before and after the PR.
https://indico.cern.ch/event/1410982/contributions/5930990/attachments/2860991/5005504/first%20study%20of%20cut%20difference%20at%20low%20and%20high%20pt.pdf
Although the overall efficiency doesn't change much, the pT5 efficiency is increased.
before bug fix:
http://uaf-10.t2.ucsd.edu/~yagu/SDL_GPU_plots/T3_remove_redundant/pT3_pt_redef/new_def_PU200_NEVT-1_a9bf9a-PU200/compare/TC_base_0_0_eff_pt.html
after bug fix:
http://uaf-10.t2.ucsd.edu/~yagu/SDL_GPU_plots/high_pt_cuts/pT5_rz_low_pt_new_pt_def_PU200_NEVT-1_ac7ce5D-PU200/compare/TC_base_0_0_eff_pt.html

**Review by slava77 — COMMENTED** [review]
The code looks OK.
However, the comparisons are suggestive that there may be a loss in the total efficiency, which is not really expected since the selections are less strict with this PR>

As discussed yesterday the plan is to check on a larger sample.

**Comment by YonsiG** [comment]
Checking with a large sample, PU200 1000 events. Color codes are reverted with the CI check: red is after this PR, black is the master before. This is very hard to see the efficiency change for the highest pt bin.

Screenshot 2024-05-28 at 7 05 37 PM

The full comparison is linked here.
http://uaf-10.t2.ucsd.edu/~yagu/SDL_GPU_plots/high_pt_cuts/large_samples_comparison_PR405_1e1ebc-PU200_f2dfe2-PU200/compare/TC_eff_base_0.html

**Comment by slava77** [comment]
> The full comparison is linked here.
> http://uaf-10.t2.ucsd.edu/~yagu/SDL_GPU_plots/high_pt_cuts/large_samples_comparison_PR405_1e1ebc-PU200_f2dfe2-PU200/compare/TC_eff_base_0.html

the same folder following up from this link apparently shows [large changes in the fake rate](http://uaf-10.t2.ucsd.edu/~yagu/SDL_GPU_plots/high_pt_cuts/large_samples_comparison_PR405_1e1ebc-PU200_f2dfe2-PU200/compare/fakerate.html)

while the bot tests show no difference
https://github.com/SegmentLinking/TrackLooper/pull/405#issuecomment-2125007216

Does the comparison include also the pt definition change?
Is the idea that it doesn't affect the sim-pt-based efficiency plot?

**Review by slava77 — APPROVED** [review]

**Comment by YonsiG** [comment]
> > The full comparison is linked here.
> > http://uaf-10.t2.ucsd.edu/~yagu/SDL_GPU_plots/high_pt_cuts/large_samples_comparison_PR405_1e1ebc-PU200_f2dfe2-PU200/compare/TC_eff_base_0.html
> 
> the same folder following up from this link apparently shows [large changes in the fake rate](http://uaf-10.t2.ucsd.edu/~yagu/SDL_GPU_plots/high_pt_cuts/large_samples_comparison_PR405_1e1ebc-PU200_f2dfe2-PU200/compare/fakerate.html)
> 
> while the bot tests show no difference [#405 (comment)](https://github.com/SegmentLinking/TrackLooper/pull/405#issuecomment-2125007216)
> 
> Does the comparison include also the pt definition change? Is the idea that it doesn't affect the sim-pt-based efficiency plot?



> > The full comparison is linked here.
> > http://uaf-10.t2.ucsd.edu/~yagu/SDL_GPU_plots/high_pt_cuts/large_samples_comparison_PR405_1e1ebc-PU200_f2dfe2-PU200/compare/TC_eff_base_0.html
> 
> the same folder following up from this link apparently shows [large changes in the fake rate](http://uaf-10.t2.ucsd.edu/~yagu/SDL_GPU_plots/high_pt_cuts/large_samples_comparison_PR405_1e1ebc-PU200_f2dfe2-PU200/compare/fakerate.html)
> 
> while the bot tests show no difference [#405 (comment)](https://github.com/SegmentLinking/TrackLooper/pull/405#issuecomment-2125007216)
> 
> Does the comparison include also the pt definition change? Is the idea that it doesn't affect the sim-pt-based efficiency plot?

sorry, I forgot to rebase the master after the pt change PR get merged. I will update a new comparison

**Comment by YonsiG** [comment]
Sorry, I forgot to rebase the master after the pt change PR get merged.New link here and also updated in previous comments
http://uaf-10.t2.ucsd.edu/~yagu/SDL_GPU_plots/high_pt_cuts/large_samples_comparison_PR405_4d67cf-PU200_bf5196-PU200/compare/

**Pull request merged**
