### PR TITLE
working TCE time reduction

### PR DESCRIPTION
**Pull request by tresreid**
Redoes the kernel launch and distribution of work for threads in the TCE creation kernel.
Validation: https://www.classe.cornell.edu/~mgr85/www/SegmentLinking_keep/PR113/

### CODE REVIEW

**Comment by tresreid** [comment]
timing: 
image

**Comment by slava77** [comment]
I'm curious about the apparently bad scaling of the TCE kernel vs the number of streams. Everything else seems to be roughly linear. Perhaps it's just round-offs. 
@tresreid 
Please add one more significant digit to the printout values below 2ms.

**Comment by tresreid** [comment]
image

**Comment by slava77** [comment]
> image

thanks. Well, this doesn't look like a round-off; OTOH, perhaps there is an issue in the timing resolution at low values.
e.g. 0.06 for s=1 seems too small. 
Is this an average over many events? how many?

**Comment by tresreid** [comment]
Ok Actually i don't think this is real. I think i missed up somewhere.

**Pull request closed without merging**
