### PR TITLE
Fix duplicate rate bug

### PR DESCRIPTION
**Pull request by sgnoohc**
- Fixed the duplicate rate bug
- Some minor fix in the hipergator setup

New perf plot.
http://uaf-10.t2.ucsd.edu/~phchang/performance/performance/FixDR_579b9dD-PU200/summary/

### CODE REVIEW

**Comment by sgnoohc** [comment]
comparison plot against master
http://uaf-10.t2.ucsd.edu/~phchang/performance/performance/FixDR_579b9d-PU200_579b9dD-PU200/compare/TC_eff_base_0.html
http://uaf-10.t2.ucsd.edu/~phchang/performance/performance/FixDR_579b9d-PU200_579b9dD-PU200/compare/fakerate.html
http://uaf-10.t2.ucsd.edu/~phchang/performance/performance/FixDR_579b9d-PU200_579b9dD-PU200/compare/duplrate.html

only duplrate affected

**Comment by IHateLinus** [comment]
Seems like T5 Dup/FR are not filled, or at least I can’t see them.

Do you happen to have the stacked plots of these?

**Comment by sgnoohc** [comment]
After fix fake rate:
http://uaf-10.t2.ucsd.edu/~phchang/performance/performance/FixDR_579b9dD-PU200/summary/TC_fakerate_etacoarsezoom.html
http://uaf-10.t2.ucsd.edu/~phchang/performance/performance/FixDR_579b9dD-PU200/summary/TC_fakerate_pt.html

after fix duplicate rate:
http://uaf-10.t2.ucsd.edu/~phchang/performance/performance/FixDR_579b9dD-PU200/summary/TC_duplrate_etacoarsezoom.html
http://uaf-10.t2.ucsd.edu/~phchang/performance/performance/FixDR_579b9dD-PU200/summary/TC_duplrate_ptzoom.html

**Comment by IHateLinus** [comment]
FR is func of pt, and dup eta.
Do you have FR as func of eta

**Comment by VourMa** [comment]
For documentation:
http://uaf-10.t2.ucsd.edu/~phchang/talks/PhilipChang20230317_LST_FixDR.pdf

**Review by VourMa — APPROVED** [review]
Looks good to me, merging...

**Pull request merged**
