### PR TITLE
speedup in startup and hit loading

### PR DESCRIPTION
**Pull request by slava77**
for 20 events one stream
Real Time (as of 3dbc4c3) :      23.9 s->  13.1 s.

From igprof report https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/sdl/ig.pp.3dbc4c3.rerun2 vs https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/sdl/ig.pp.16776d3-addInputs2.m8clx (in perf counts, which I think are about the same as seconds)
- `addInputsToLineSegmentTrackingPreLoad`: 2.31 -> 1.95
- `SDL::initModules`: 3.46 -> 2.07
- `SDL::initHits`: 10.27 -> 1.43

### CODE REVIEW

**Comment by slava77** [comment]
I pushed an update in 059d27c.
Now the number of constructed objects agrees.
The counts in the higher level objects seem to fluctuate even in the master.

**Comment by tresreid** [comment]
validation looks ok: https://www.classe.cornell.edu/~mgr85/www/SegmentLinking_keep/PR154/eff_plots__GPU_explicit_cache_b0b8323_PU200/#1.5

**Comment by tresreid** [comment]
I'm not sure, but I think this PR lead to some slowdown in the runtime. Did you see this as well or understand why this might be the case?

**Comment by slava77** [comment]
here is what I see on 200 events (new = 9e6ae0f; old = 529c823)
```
   Evt    Hits       MD       LS      T3       T5       pLS       pT5      pT3      TC       TCE      Event      Short             Rate
   old      2.2      3.7      3.5      3.2      3.4      5.0      6.3      5.9      6.8      5.7      45.7      38.5+/-  4.3      51.6   explicit_cache[s=1]
   new      2.4      4.2      3.2      3.2      3.3      5.0      6.2      5.7      9.2      5.8      48.3      40.9+/-  4.9      51.7   explicit_cache[s=1]
```

**Comment by slava77** [comment]
in my case the increase is in `removeDupQuintupletsInGPUv2`, on 20 events from 2.54ms to 4.86ms; about twice as slow

**Comment by tresreid** [comment]
I think i see something similar. Other multiplicities have not changed so idk why this is running slower.

**Pull request merged**
