### PR TITLE
T4 from T3

### PR DESCRIPTION
**Pull request by tresreid**
T4 objects made from T3 objects for all versions toggled by -DT4FromT3 in the SDL/Makefile.
This PR is built on top of PR #32 
Validation plots showing a very slight (negligible) decrease in efficiency: https://www.classe.cornell.edu/~mgr85/SegmentLinking_keep/PR34/efficiencies/
Timing results:
image

### CODE REVIEW

**Comment by tresreid** [comment]
New multiplicies for the T4 and TC objects are shown here:
image

**Comment by beiwang2003** [comment]
The bugs associated with the inconsistency between lnx and phi are at createTrackCandidates() function. It seems this function is not modified in this PR. Can you please confirm? @tresreid If that is the case, the bug won't propagate in this PR.

**Comment by tresreid** [comment]
> The bugs associated with the inconsistency between lnx and phi are at createTrackCandidates() function. It seems this function is not modified in this PR. Can you please confirm? @tresreid If that is the case, the bug won't propagate in this PR.

This PR doesn't include your PR #33 . But the new grid approach was lifted from there. So i don't know what the bug is or if i wrote it out in the newgrid for making T4 from T3 (createTracklets() )

**Comment by beiwang2003** [comment]
> > The bugs associated with the inconsistency between lnx and phi are at createTrackCandidates() function. It seems this function is not modified in this PR. Can you please confirm? @tresreid If that is the case, the bug won't propagate in this PR.
> 
> This PR doesn't include your PR #33 . But the new grid approach was lifted from there. So i don't know what the bug is or if i wrote it out in the newgrid for making T4 from T3 (createTracklets() )

It looks fine to me. The bug was not included in the createTracklets().

**Comment by tresreid** [comment]
Updated merging all the recent PRs. The validation plots have been updated in the same place. The new times are below.
image

**Comment by bsathian** [comment]
Things look good. Let us not enable -DT4FromT3 by default. So I'll comment it out for the time being

**Pull request merged**
