### PR TITLE
make md occupancy cut in different eta modules

### PR DESCRIPTION
**Pull request by YonsiG**

### CODE REVIEW

**Comment by YonsiG** [comment]
The timing results are here.
Screen Shot 2022-04-11 at 3 09 09 PM

**Comment by YonsiG** [comment]
The efficiency plots comparisons are here 
http://uaf-10.t2.ucsd.edu/~yonsi/SDL_GPU_plots/md_occupancy_9999_by_region/eff_comparison_plots__76c15c6_explicit_9afc360_explicit_PU200/

**Comment by YonsiG** [comment]
and timing results before this is shown below.
image

**Comment by YonsiG** [comment]
The timing results are here

**Comment by YonsiG** [comment]
closed by mistake...

**Comment by YonsiG** [comment]
Screen Shot 2022-04-12 at 10 07 25 PM

**Comment by tresreid** [comment]
There are 2 Frees missing in explicit (and x cache) version. The Unified version breaks at runtime. Please fix

**Pull request merged**
