### PR TITLE
Addig r_vertex plot. LSTPerformanceWeb not updated yet.

### PR DESCRIPTION
**Pull request by sgnoohc**
- added rvertex plot.
- LSTPerformanceWeb has not been updated yet, so the plot not visible in html yet. (see https://github.com/SegmentLinking/TrackLooper/issues/277)

### CODE REVIEW

**Comment by slava77** [comment]
as mentioned in the chat

https://github.com/cms-sw/cmssw/blob/master/Validation/RecoTrack/python/TrackingParticleSelectionsForEfficiency_cff.py#L27

MTV has an upper cut on vertex_xy at 60 cm for the plots vs vtx position.
We should perhaps keep it as well.  (even if e.g. T5 reconstruction is impossible already with 40 cm in the barrel)

**Comment by VourMa** [comment]
@sgnoohc Could you please comment on the status of this PR? Is it meant to be merged? If so, is it complete?

**Comment by slava77** [comment]
> @sgnoohc Could you please comment on the status of this PR? Is it meant to be merged? If so, is it complete?

ping

**Comment by sgnoohc** [comment]
I believe I meant to.

I believe I failed to assign a reviewer.

It's rather a minimal change, so I think the review would be simiple.

Philip

--
Dr. P. Chang, Asst. Prof., University of Florida
***@***.***
________________________________

**Review by VourMa — APPROVED** [review]
Thanks @ariostas for finalizing this PR. I am approving and merging but, for completeness, please also post the validation with the added plots in the PR comments.

**Pull request merged**
