### PR TITLE
Explicit Tracks and Pixels

### PR DESCRIPTION
**Pull request by tresreid**
Adds explicit memory management for track candidates and includes pixel update

### CODE REVIEW

**Comment by tresreid** [comment]
Timing results
segments see slowdown at 2ef9673. tracklets at 25f4424. 
EXPLICIT
events minidoublets segments triplets pixels tracklets tracks
0       0.0200920   0.158488   0.0779729   0.00927496   0.393730   0.133335
1       0.0496609   0.124602   0.0636230   0.00924802   0.320307   0.105436
2       0.0294802   0.151203   0.0711460   0.00948405   0.386847   0.162223
3       0.0413799   0.147986   0.0718019   0.00924301   0.378572   0.156138
4       0.0497320   0.113414   0.0576169   0.00922418   0.306728   0.105850
5       0.0462990   0.143142   0.0639701   0.00930691   0.346307   0.139289
6       0.0496399   0.110864   0.0500190   0.00951004   0.289279   0.111758
7       0.0484991   0.134651   0.0623441   0.00973797   0.338394   0.155233
8       0.0512090   0.134068   0.0670731   0.00927806   0.368839   0.135691
9       0.0514700   0.133167   0.0633321   0.00927901   0.320885   0.130110

Explicit cache
events minidoublets segments triplets pixels tracklets tracks
0       0.179161   0.183699   0.0928791   0.0231519   0.411729   0.169467
1       0.0148640   0.136685   0.0571740   0.000694036   0.311238   0.134206
2       0.0169091   0.156809   0.0780139   0.000788927   0.405199   0.170052
3       0.0168519   0.156297   0.0692651   0.000714064   0.405548   0.154471
4       0.0142851   0.131111   0.0535538   0.000511169   0.285697   0.108549
5       0.0168819   0.148701   0.0669041   0.000693083   0.360177   0.138778
6       0.0138280   0.121911   0.0519140   0.000548124   0.303803   0.100359
7       0.0156040   0.142185   0.0669971   0.000779867   0.369248   0.132644
8       0.0151720   0.147788   0.0563302   0.000885010   0.352412   0.125740
9       0.0149691   0.139886   0.0585110   0.000735998   0.332103   0.129947

Unified 
events minidoublets segments triplets pixels tracklets tracks
0       0.0582042   0.202379   0.172931   0.0254850   0.261446   0.134410
1       0.0549810   0.190522   0.162190   0.0183148   0.194482   0.0980859
2       0.0445511   0.218415   0.165747   0.0180490   0.282701   0.142224
3       0.0450132   0.203686   0.157428   0.0237210   0.269711   0.136335
4       0.0431249   0.175609   0.149154   0.0188029   0.188841   0.0817270
5       0.0449700   0.186992   0.154847   0.0180550   0.240404   0.110790
6       0.0423219   0.173694   0.146121   0.0180838   0.178828   0.0806921
7       0.0443039   0.192027   0.160053   0.0181701   0.235389   0.133364
8       0.0445061   0.179054   0.165154   0.0181849   0.220895   0.108361
9       0.0444210   0.173684   0.152139   0.0183380   0.212676   0.104047

Unified cache
events minidoublets segments triplets pixels tracklets tracks
0       0.216531   0.209162   0.171907   0.0254221   0.264121   0.127569
1       0.0317011   0.132118   0.0690441   0.0205219   0.218297   0.0963991
2       0.0331452   0.158542   0.0847321   0.0179589   0.328748   0.146786
3       0.0333710   0.169789   0.0837290   0.0185902   0.314290   0.119700
4       0.0315540   0.126486   0.0653019   0.0118210   0.252136   0.0937908
5       0.0334449   0.150148   0.0751970   0.0180559   0.314390   0.115073
6       0.0309160   0.122269   0.0708480   0.0181410   0.247176   0.0826190
7       0.0318201   0.139252   0.0769372   0.0179560   0.326207   0.127965
8       0.0330331   0.145046   0.0795140   0.0180891   0.349454   0.103266
9       0.0324070   0.161843   0.0725889   0.0179791   0.310302   0.0892220

**Comment by slava77** [comment]
> segments see slowdown at [2ef9673](https://github.com/SegmentLinking/TrackLooper/commit/2ef9673b3178e14534a99d9021f9c90bf92be810). tracklets at [25f4424](https://github.com/SegmentLinking/TrackLooper/commit/25f44243e094bbc55761d9e387aeb58dfb06d8c4).
> EXPLICIT
> events minidoublets segments triplets pixels tracklets tracks
> 0 0.0200920 0.158488 0.0779729 0.00927496 0.393730

there are so many numbers in this kind of summary that I end up ignoring this data.
Perhaps it's just me, but I'd still suggest to parse the numerical values first to something that's easily readable and then post

**Comment by tresreid** [comment]
I've changed the final timing report to be better formatted and report times in ms. I hope this is better.
Explicit
events minidoublets segments triplets pixels tracklets tracks
0   20.52   159.92   73.88   9.31   373.87   160.99
1   51.03   178.33   69.83   9.12   345.13   118.09
2   30.85   145.11   74.09   9.12   411.33   189.16
3   34.39   145.35   68.53   9.12   387.61   144.36
4   49.20   112.07   57.54   9.21   264.85   96.33
5   39.52   142.09   64.83   9.19   344.04   131.90
6   48.94   112.68   54.97   9.19   285.99   90.80
7   50.05   140.98   64.71   9.23   348.15   134.45
8   49.29   138.78   61.32   9.15   315.37   128.10
9   51.86   131.85   63.70   9.16   334.65   117.49

Explicit cache
events minidoublets segments triplets pixels tracklets tracks
0  182.49  153.65   80.51   25.02 376.99   162.76
1   13.40   117.12   51.67   0.47   311.62   102.86
2   15.09   144.92   67.40   0.53   399.29   167.53
3   15.62   143.53   64.35   1.08   377.74   166.52
4   13.79   122.14   51.46   0.70   293.61   113.33
5   16.41   152.55   68.94   0.50   375.22   131.62
6   12.49   111.59   48.64   0.53   288.24   96.90
7   13.97   142.93   64.29   0.52   363.68   137.95
8   13.95   128.14   56.23   0.52   319.55   132.80
9   13.82   125.43   52.78   0.81   318.47   124.63

Unified 
events minidoublets segments triplets pixels tracklets tracks
0   55.00   199.88   156.74   13.05   264.31   115.91
1   41.89   170.90   147.25   18.17   205.77   102.69
2   43.61   205.37   165.83   13.61   270.91   146.56
3   41.99   177.51   168.37   25.28   268.52   133.97
4   50.83   170.39   146.23   23.18   183.79   78.38
5   56.01   183.64   155.40   13.29   231.29   114.37
6   41.15   171.11   149.26   18.11   181.54   80.84
7   54.39   173.08   155.40   17.88   228.90   118.23
8   42.53   190.83   152.06   18.09   218.89   112.44
9   41.79   180.58   153.09   25.29   225.24   109.96

Unified cache
events minidoublets segments triplets pixels tracklets tracks
0 222.65   189.55   162.10   25.10   254.75   128.08
1   28.29   126.21   70.74   13.16   258.80   96.40
2   34.17   160.68   103.63   23.94   323.16   164.92
3   35.78   146.59   91.00   13.57   365.32   120.91
4   30.29   141.60   80.74   21.24   280.46   81.32
5   32.70   155.64   75.24   13.41   348.43   100.95
6   30.34   120.00   60.64   13.57   280.56   89.27
7   31.35   158.80   80.53   13.37   355.30   122.41
8   34.10   170.60   85.65   18.36   352.09   99.01
9   31.34   149.01   77.17   12.74   330.22   97.42

**Comment by beiwang2003** [comment]
Here are the test results of different versions:
1. unified, non-cached, nvprof (passed), cuda-memcheck (hanging)
2. unified, cached, nvprof (passed), cuda-memcheck (hanging)
3. explicit, non-cashed, nvprof (failed) with the following error message:
Adding Pixel Segments!
Error in <TROOT::TVector2::Phi_mpi_pi>: function called with NaN
Error in <TROOT::TVector2::Phi_mpi_pi>: function called with NaN
 Reco Pixel Tracklet start
Reco Pixel Tracklet processing time: 0.0114791 secs
Reco Tracklet start
Reco Tracklet processing time: 0.405733 secs
# of Tracklets produced: 86588
# of Tracklets produced layer 1-2-3-4: 31700
# of Tracklets produced layer 2-3-4-5: 25466
# of Tracklets produced layer 3-4-5-6: 16721
# of Tracklets produced layer 4: 1208
# of Tracklets produced layer 5: 0
# of Tracklets produced layer 6: 0
Reco TrackCandidate start
sync failed with error : an illegal memory access was encountered
4. explicit, cached (failed) with the error message below:
Adding Pixel Segments!
Error in <TROOT::TVector2::Phi_mpi_pi>: function called with NaN
Error in <TROOT::TVector2::Phi_mpi_pi>: function called with NaN
 Reco Pixel Tracklet start
terminate called after throwing an instance of 'std::runtime_error'
  what():  
allocate.cc, line 44:
cudaCheck(allocator::getCachingDeviceAllocator().DeviceAllocate(dev, &ptr, nbytes, stream));
cudaErrorMemoryAllocation: out of memory

@tresreid there seems a bug in the explicit memory version. Can you double check?

**Comment by tresreid** [comment]
Error in TROOT::TVector2::Phi_mpi_pi: function called with NaN happens in all cases, including unified memory. I had assumed this was a non-issue since that is from what @bsathian has. Maybe he can confirm
I done see an illegal memory access when i run nvprof though. Can you try again? does this happen consistently for you?
As for the cached memory, I guess you are running on the phi 3 gpus or something with less memory (~16 GB?). We had seen this problem before, but it's just that we are allocating too much memory. and this is made worse because of the inclusion of the pixels. I think this is an issue to tackle later though. not in this PR

**Comment by beiwang2003** [comment]
@tresreid Can you also remind me why we choose the full explicit approach at the end? The new grid method will need to have nMD, nSegments, etc information on the CPU to find the optimal threads and block numbers.

**Comment by bsathian** [comment]
> Error in TROOT::TVector2::Phi_mpi_pi: function called with NaN happens in all cases, including unified memory. I had assumed this was a non-issue since that is from what @bsathian has. Maybe he can confirm

this happens because the delta phi for a pixel line segment is computed and then used for selection, and for some pixel line segments the delta phi computation fails, but this doesn't matter because these pixel line segments are rejected for being NaNs

**Comment by tresreid** [comment]
@beiwang2003 , for the new grid method, we would either have to transfer the necessary data back to the CPU (which i don't think would be difficult to do and shouldn't be significantly slower than what is done now with unified memory since a transfer back to host would have to be done there anyway) or we need to run that method on the gpu.  I think unified memory isn't supposed to be used at all in our final version due to cms restrictions.

**Comment by beiwang2003** [comment]
Yes, it is easy to transfer the data back with the new grid method. I just feel using unified memory for nMDs, nSegments etc is the best considering both performance and ease of programming. If CMS has restrictions to use the unified method, let's just remove it completely. @tresreid

**Comment by beiwang2003** [comment]
@tresreid the explicit and non-cached version failed with segmentation violation. Can you check and address the issue? 

Adding Pixel Segments!
Error in <TROOT::TVector2::Phi_mpi_pi>: function called with NaN
Error in <TROOT::TVector2::Phi_mpi_pi>: function called with NaN
 Reco Pixel Tracklet start
Reco Pixel Tracklet processing time: 0.011183 secs
Reco Tracklet start
Reco Tracklet processing time: 0.384819 secs
# of Tracklets produced: 86588
# of Tracklets produced layer 1-2-3-4: 31700
# of Tracklets produced layer 2-3-4-5: 25466
# of Tracklets produced layer 3-4-5-6: 16721
# of Tracklets produced layer 4: 1208
# of Tracklets produced layer 5: 0
# of Tracklets produced layer 6: 0
Reco TrackCandidate start
sync failed with error : an illegal memory access was encountered

 *** Break *** segmentation violation

**Comment by tresreid** [comment]
This is running by cloning my pixels branch from my repo in a fresh directory. I do not see this issue. Have you changed anything?
image

**Comment by beiwang2003** [comment]
@tresreid This is my version:commit 9f36dfd72. The only thing I changed is the Makefile. This is my Makefile:

`CCSOURCES=$(wildcard *.cc)
CCOBJECTS=$(CCSOURCES:.cc=.o)
CCHEADERS=$(CCSOURCES:.cc=.h)

CUSOURCES=$(wildcard *.cu)
CUOBJECTS=$(CUSOURCES:.cu=.o)
CUHEADERS=$(CUSOURCES:.cu=.cuh)
LIB=sdl.so
# AMD Opteron and Intel EM64T (64 bit mode) Linux with gcc 3.x                                                                  
#CXX           = g++4                                                                                                           
CXX           = nvcc
CXXFLAGS      =  -g --compiler-options -Wall --compiler-options -Wshadow --compiler-options -Woverloaded-virtual --compiler-opt\
ions -fPIC --compiler-options -fopenmp -dc -lineinfo --ptxas-options=-v --cudart shared -arch=compute_52 -I/mnt/data1/dsr/cub
#LD            = g++4                                                                                                           
LD            = nvcc
#LDFLAGS       = -g -O2                                                                                                         
SOFLAGS       = -g -shared --compiler-options -fPIC --cudart shared -arch=compute_52
MEMFLAG       = -DExplicit_MD -DExplicit_Seg -DExplicit_Tracklet -DExplicit_Trips -DExplicit_Track
PRINTFLAG     = -DAddObjects
#CACHEFLAG     = -DCACHE_ALLOC                                                                                                  
# how to make it                                                                                                                
#                                                                                                                               

%.o : %.cu %.cuh
        $(LD) -x cu $(CXXFLAGS) $(LDFLAGS) $(ROOTLIBS) $(MEMFLAG) $(PRINTFLAG) $(CACHEFLAG) $< -o $@

%.o : %.cc %.h
        $(LD) $(CXXFLAGS) $(LDFLAGS) $(ROOTLIBS) $(MEMFLAG) $(PRINTFLAG) $(CACHEFLAG) $< -o $@



$(LIB):$(CCOBJECTS) $(CUOBJECTS)
        $(LD)  $(SOFLAGS) $^ -o $@

all: $(LIB)
clean:
        rm -f *.o \
        rm -f *.d \
        rm -f *.so \'

**Comment by beiwang2003** [comment]
@tresreid btw, the code works fine by turning of #-DExplicit_Track.

**Comment by beiwang2003** [comment]
Now I am switching to lnx7188. I've seen very high number of some CUDA calls (e.g., cudaDeviceSynchronize, cudaMalloc etc). This is tested w/o explicit and cached memory. See:==17052== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:  100.00%  30.209ms     23540  1.2830us  1.2470us  1.9200us  [CUDA memcpy HtoD]
      API calls:   54.49%  1.31471s     23549  55.828us  2.9150us  268.00ms  cudaDeviceSynchronize
                   12.94%  312.35ms        62  5.0379ms  6.5300us  310.98ms  cudaMallocManaged
                    9.25%  223.28ms        61  3.6603ms  17.091us  35.387ms  cudaFree
                    8.81%  212.57ms     23540  9.0300us  5.5400us  1.2491ms  cudaMalloc
                    8.03%  193.79ms     23540  8.2320us  6.8430us  1.2455ms  cudaMemcpy
                    6.27%  151.22ms     23546  6.4220us  5.6370us  3.1557ms  cudaLaunchKernel
                    0.07%  1.7927ms         2  896.35us  882.06us  910.64us  cuDeviceTotalMem
                    0.07%  1.7298ms         5  345.97us  31.250us  1.3100ms  cudaHostAlloc
                    0.03%  812.62us         5  162.52us  11.477us  717.67us  cudaFreeHost
                    0.02%  582.47us       202  2.8830us     169ns  127.33us  cuDeviceGetAttribute
                    0.01%  127.46us         2  63.728us  26.406us  101.05us  cuDeviceGetName
                    0.00%  9.0630us         2  4.5310us  3.3220us  5.7410us  cuDeviceGetPCIBusId
                    0.00%  5.5920us         3  1.8640us     689ns  2.8200us  cuDeviceGetCount
                    0.00%  3.1380us         4     784ns     269ns  1.2300us  cuDeviceGet
                    0.00%     653ns         2     326ns     250ns     403ns  cuDeviceGetUuid

**Comment by beiwang2003** [comment]
Screen Shot 2020-12-14 at 11 49 38 AM

**Comment by beiwang2003** [comment]
@tresreid @bsathian Now I've traced back to version #e1cf33b (PR#5 ) and seen unequal number of cudaMallocManaged and cudaFree. @bsathian Can you check the issue? 
Screen Shot 2020-12-14 at 12 01 54 PM

**Comment by tresreid** [comment]
Hi @beiwang2003,
I think i should have fixed the uneven calls in malloc and frees in the latest PR (which contains all of these changes). Can you check there?

**Comment by tresreid** [comment]
Also, the high number of calls comes from loading the pixels. As of right now this is a feature and not a bug. The pixels are added by running over a loop (addPixelSegments) and then calling "addHitToEvent (or addPixToEvent)" for each pixel hit. In the future, I think the pixel loading should be reworked if we care about their timing.

**Pull request closed without merging**
