### PR TITLE
Cache alloc

### PR DESCRIPTION
**Pull request by tresreid**
Implemented cache allocation for both unified and explicit memory. Includes supporting files for cache allocation as well as memory freeing functions. Toggled by cache flag in makefile. 
Replaced struct allocation with cudaMemHost for all cases. Removed ObjectInTemp structs.
Removed old_cc folder.

### CODE REVIEW

**Review by beiwang2003 — CHANGES_REQUESTED** [review]
In cached memory allocation approach, we try to allocate fewer larger arrays instead of more smaller ones. Then we offset the pointers to get the addresses needed. I've found allocating fewer larger arrays is more efficient than larger number of smaller ones. Is this also done for non-cached allocation approach. If not, try to implement that for the non-cached allocation approach.

**Review by beiwang2003 — COMMENTED** [review]
When I compiled the code, it also compliant this:
In file included from getCachingAllocator.h:6,
                 from allocate.cc:6:
CachingDeviceAllocator.h:47:10: fatal error: /mnt/data1/dsr/cub/cub/util_debug.cuh: No such file or directory
   47 | #include </mnt/data1/dsr/cub/cub/util_debug.cuh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by tresreid** [comment]
fixed cub headers and switched all allocations to use shifted pointers in setup. 
I also added a final printout to easily grab the times alone at the end of the run. "fixing" the individual module timings by starting the clock before the creation function and stopping it right after gives a difference of 0 so I left it how it was before for now. I think this needs to be fixed later though. There seems to be a setup time associated with caching for the first event. 
Final times are:
Unified:
events minidoublets segments triplets tracklets
0 0.0553451 0.213656 0.103049 0.298826
1 0.041394 0.183624 0.0933502 0.24523
2 0.052603 0.202337 0.102486 0.293413
3 0.0424211 0.194724 0.0981219 0.29573
4 0.0522761 0.187187 0.0835099 0.209565
5 0.0418081 0.198038 0.090307 0.24768
6 0.0404551 0.171855 0.0852132 0.191193
7 0.0414481 0.18662 0.091645 0.265667
8 0.0415449 0.188021 0.0884891 0.241894
9 0.0416179 0.186284 0.085695 0.254058
unified w/cache:
events minidoublets segments triplets tracklets
0 0.217893 0.207523 0.0980248 0.29572
1 0.0314231 0.149281 0.0717971 0.2687
2 0.0330911 0.193258 0.0947042 0.419649
3 0.0327129 0.17999 0.0877359 0.408511
4 0.030967 0.141488 0.0644031 0.305051
5 0.0324271 0.165961 0.074826 0.395418
6 0.0310888 0.139407 0.0634961 0.27371
7 0.0432038 0.167507 0.0746391 0.372265
8 0.0305738 0.175473 0.0742171 0.359777
9 0.0424809 0.162495 0.0739419 0.347088
explicit
events minidoublets segments triplets tracklets
0 0.0201371 0.16137 0.076941 0.404303
1 0.0201309 0.13935 0.0590651 0.336243
2 0.021524 0.178443 0.0926039 0.446301
3 0.0211718 0.175511 0.0852511 0.445115
4 0.019227 0.137473 0.0580349 0.318828
5 0.0208139 0.158402 0.071352 0.401785
6 0.0173039 0.171548 0.0591979 0.322087
7 0.0185061 0.149453 0.061974 0.351411
8 0.018286 0.145913 0.0616059 0.3564
9 0.0193379 0.153524 0.062505 0.352971
explicit w/cache
events minidoublets segments triplets tracklets
0 0.180803 0.196533 0.096909 0.463423
1 0.0152571 0.146554 0.0598881 0.317284
2 0.016506 0.180931 0.085237 0.426286
3 0.01617 0.170701 0.0785289 0.411356
4 0.012841 0.124211 0.0518811 0.30914
5 0.014493 0.147456 0.067868 0.368232
6 0.012341 0.121689 0.0502889 0.295204
7 0.013773 0.147292 0.0660219 0.363667
8 0.014015 0.145851 0.06321 0.359564
9 0.0134549 0.141414 0.0580568 0.337498
full explicit
events minidoublets segments triplets tracklets
0 0.0193129 0.173999 0.074059 0.40565
1 0.0174229 0.137177 0.058512 0.332976
2 0.018986 0.168593 0.0792301 0.419004
3 0.02073 0.198181 0.085773 0.437072
4 0.0184891 0.150119 0.0590501 0.325932
5 0.0205381 0.160014 0.0720961 0.39856
6 0.0175271 0.134488 0.058105 0.310387
7 0.0182929 0.160322 0.0698891 0.384235
8 0.0184872 0.16136 0.0681212 0.380967
9 0.0187199 0.160475 0.0665228 0.397028
full explicit with cache:
events minidoublets segments triplets tracklets
0 0.177378 0.195034 0.0924051 0.423231
1 0.0125401 0.137807 0.055845 0.320691
2 0.0139959 0.164971 0.0777869 0.401
3 0.0139089 0.155691 0.0691309 0.394329
4 0.0118029 0.117436 0.0523539 0.303215
5 0.0134182 0.144824 0.063235 0.355886
6 0.0116789 0.124942 0.0524518 0.292608
7 0.012897 0.149932 0.063319 0.352366
8 0.013078 0.141035 0.059294 0.348341
9 0.012805 0.14275 0.064152 0.352463

**Review by beiwang2003 — APPROVED** [review]
I've used nvprof to run the code and found we have unequal number of cudaMallocManaged and cudaFree calls for the unified memory approach. It seems cudaFree is missing for some objects. I am wondering where the members of the MD, segments, etc struct are being deleted?

**Review by beiwang2003 — CHANGES_REQUESTED** [review]
sorry, approve it by mistake earlier

**Comment by beiwang2003** [comment]
By the way, I've seen longer time spending on Tracklets kernel for unified memory approach from the latest version. See the screenshot. Do you know why is this?
Screen Shot 2020-11-18 at 10 23 58 PM

**Review by beiwang2003 — APPROVED** [review]

**Pull request merged**
