### PR TITLE
Thread overlap

### PR DESCRIPTION
**Pull request by tresreid**
Changes the division of threads and blocks. Runs kernels using a for loop over the threads. Can change the maximum number of blocks in kernel.cuh to control GPU usage.

### CODE REVIEW

**Comment by tresreid** [comment]
validation plots: https://www.classe.cornell.edu/~mgr85/www/SegmentLinking_keep/PR93/

**Comment by tresreid** [comment]
Timing:
image

**Comment by slava77** [comment]
TC got slower, right?
is it clear why?

**Comment by tresreid** [comment]
I didn't properly set the blocks there. It is fixed now. for 80 blocks we get this: 
image

**Comment by tresreid** [comment]
All fixed timings:
image

**Pull request merged**
