### PR TITLE
pT3 newgrid + bugfixes

### PR DESCRIPTION
**Pull request by bsathian**

### CODE REVIEW

**Comment by bsathian** [comment]
plots here

http://uaf-10.t2.ucsd.edu/~bsathian/SDL/pT3_efficiency/pT3_newgrid_bugfix/

**Comment by tresreid** [comment]
I think you are missing 5 cudaFrees and 1 cudaFreeHost

**Comment by tresreid** [comment]
The fix to the pT2 newgrid method does show some improvement but the results are still not exactly the same as the nested version.

**Comment by tresreid** [comment]
Free mismatch will be handled later.

**Pull request merged**
