### PR TITLE
factorize addXXXObectsToEventExplicit into GPU and optional CPU functions

### PR DESCRIPTION
**Pull request by tresreid**
Moves all necessary GPU functionality from the addXXXObjectsToEventExplicit to kernels called addXXXRangesToEvent.
The remaining CPU function remains but is only run when -v >=2. 
Also does some cleanup, removes the addObjects flag in the makefile and removes instances of nLowerModule transfers (as they are not needed).

### CODE REVIEW

**Comment by tresreid** [comment]
Timing: 
image

Validation: https://www.classe.cornell.edu/~mgr85/SegmentLinking_keep/PR273/PR273_PU200_NEVT-1_6f60aa-PU200/summary/

Comparison to master (before PR271): https://www.classe.cornell.edu/~mgr85/SegmentLinking_keep/PR273/PR273comparison_398270-PU200_6f60aa-PU200/summary/

**Comment by tresreid** [comment]
Summary of new kernel times:
image

**Comment by tresreid** [comment]
And mem transfer times:
image

**Comment by VourMa** [comment]
@tresreid I would like to ask a clarification on the memory transfers. What is the command that is used to measure those? 124 calls amounting to 80ms of DtoH memcpys sounds too much to me. Due to this, I did my own test, running the following command:
```
nvprof sdl -i PU200 -n 1 -w 0
```
in three cases and I wrote down the calls:
- Master before PR #272: 66 DtoH memcpy calls
- Master after PR #272 (current master): 58 DtoH memcpy calls
- This PR (#273): 27 DtoH memcpy calls

In my measurements, the gain is huge (over 50% reduction). I just would like to understand what your measurements mean.

**Comment by tresreid** [comment]
>nvprof sdl -i PU200 -v 2 -n 1 -s 1
which yields 141 DtoH
>nvprof sdl -i PU200 -v 1 -n 1 -s 1
yields 118
>nvprof sdl -i PU200 -v 0 -n 1 -s 1
yields 118
>nvprof sdl -i PU200 -n 1 -w 0
yields 21
So I guess -w is set to 1 by default. Sorry I had forgotten about this.
These results are all for PR274

**Review by VourMa — COMMENTED** [review]
The PR is essential ready to be merged. My only small comment would be to have a more descriptive flag than `addObjects` for running the `addXXXObjectsToEventExplicit` functions, maybe at least mentioning that it involves transfers to CPU?

**Review by VourMa — APPROVED** [review]
Taking a look at the other PR, I think that making a trivial change to this one would complicate things needlessly. I am approving and merging this one and you could consider improving the `addObjects` flag as an additional commit to PR #274.

**Pull request merged**
