### PR TITLE
Sync latest standalone developments with CMSSW class

### PR DESCRIPTION
**Pull request by VourMa**
This PR brings the CMSSW class up to speed with the latest standalone developments by properly initializing the `SDL::Event` object. It also simplifies the CMSSW input logic, dropping the selection based on the pixel seed iteration, as this is controlled by the module input tags in CMSSW.

The PR has been tested by running the CMSSW configuration on a few events and verifying that the TrackCandidates are the same.

Coupled with SegmentLinking/cmssw#9.

### CODE REVIEW

**Comment by GNiendorf** [comment]
Is the code in code/core/trktree.cc relating to "see_algo" still necessary? I'm not sure what trktree.cc is used for to be honest, but I saw that it has references to the "see_algo" variable.

**Comment by VourMa** [comment]
> Is the code in code/core/trktree.cc relating to "see_algo" still necessary?

Yes. When loading the pixel seeds from the tracking NTuple, pixel seeds from all iterations are included. Based on what Phase-2 HLT setup was using and some studies done in the past (PR #175 and [plots](https://www.classe.cornell.edu/~evourlio/www/SDL_GPU/trkIterAlgoComp/)), we settled (for now) to including only initialStep and highPtTripletStep pixel seeds. This selection is performed with the `see_algo` variable in `code/core/trktree.cc`. The latter file also prepares the LST input in the proper format.

For CMSSW, we control explicitly pixel seeds from which iterations to include ([here](https://github.com/SegmentLinking/cmssw/blob/52f4284ef0d81c39ca9a4339aa478a8498149004/RecoTracker/LST/plugins/LSTPixelSeedInputProducer.cc#L57-L58)), so no need select the pixel seeds also downstream, hence the simplification (which also simplifies the CMSSW side as well).

**Review by GNiendorf — APPROVED** [review]
Looks good to me. I'll approve the PR for now and let @tresreid look it over and merge.

**Comment by tresreid** [comment]
Looks good to me.

**Pull request merged**
