### PR TITLE
Occupancy reduction

### PR DESCRIPTION
**Pull request by YonsiG**

### CODE REVIEW

**Comment by bsathian** [comment]
@YonsiG can you resolve the conflicts?

**Comment by YonsiG** [comment]
I've resolved!

**Comment by slava77** [comment]
We usually do not merge own PRs in this repository.

For self-documentation, please provide a link to the validation plots and post the timing measurements in the PR description.
Thank you.

**Comment by YonsiG** [comment]
http://uaf-10.t2.ucsd.edu/~yonsi/SDL_GPU_plots/99_99change/eff_plots__GPU_explicit_a14caa3_PU200/ these are the efficiency plots.

**Comment by YonsiG** [comment]
I'm sorry for merging it myself......... 
This is the timing result
Screen Shot 2022-03-12 at 7 50 41 PM

**Pull request merged**
